version: '3.8'

services:
  lms_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_app
    restart: "no"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - lms_db

  lms_nginx:
    image: nginx:alpine
    container_name: lms_nginx
    restart: "no"
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - lms_app

  lms_db:
    image: postgres:16-alpine
    container_name: lms_postgres
    restart: "no"
    environment:
      POSTGRES_DB: leave_management_system
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  lms_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lms_pgadmin
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lms.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - laravel
    depends_on:
      - lms_db

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
